<a href="https://colab.research.google.com/github/24wh1a05m5-debug/NASCOM-LAB-CSE-B/blob/main/CaseStudy_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
battery_data=[[0,32,400,20,95],
              [1,35,395,22,88],
              [2,38,390,25,80],
              [4,42,380,30,60],
              [5,45,375,32,48]]
print("Battery Sensor Readings")
for data in battery_data:
  print("Time:",data[0],"h")
  print("Temperature:",data[1],"degree Celsius")
  print("Voltage:",data[2],"v","Current:",data[3],"A","Charge:",data[4],"%")
for data in battery_data:
  temperature=data[1]
  charge=data[4]
  if temperature>40:
    print("Time",data[0],":","High Temperature Alert")
  else:
    print("Time",data[0],":","Normal Temperature")
  if charge<50:
    print("Time",data[0],":","Low Battery Alert")
  else:
    print("Time",data[0],":","Normal Battery")
def battery_status(charge):
  if charge>70:
    return "High"
  elif charge>50:
    return "Medium"
  else:
    return "Low"
  print("\nBattery Status")
  for data in battery_data:
    print("Time",data[0],":",battery_status(data[4]))

Battery Sensor Readings
Time: 0 h
Temperature: 32 degree Celsius
Voltage: 400 v Current: 20 A Charge: 95 %
Time: 1 h
Temperature: 35 degree Celsius
Voltage: 395 v Current: 22 A Charge: 88 %
Time: 2 h
Temperature: 38 degree Celsius
Voltage: 390 v Current: 25 A Charge: 80 %
Time: 4 h
Temperature: 42 degree Celsius
Voltage: 380 v Current: 30 A Charge: 60 %
Time: 5 h
Temperature: 45 degree Celsius
Voltage: 375 v Current: 32 A Charge: 48 %
Time 0 : Normal Temperature
Time 0 : Normal Battery
Time 1 : Normal Temperature
Time 1 : Normal Battery
Time 2 : Normal Temperature
Time 2 : Normal Battery
Time 4 : High Temperature Alert
Time 4 : Normal Battery
Time 5 : High Temperature Alert
Time 5 : Low Battery Alert


In [2]:
import numpy as np
d=np.array([
    [32,400,20,95],
    [35,395,22,88],
    [38,390,25,80],
    [42,380,30,60],
    [45,375,32,48]
])
print("Shape:",d.shape)
average=np.mean(d,axis=0)
print("Average Temperature:",average[0],"degree Celsius")
print("Average Voltage:",average[1],"v")
print("Average Current:",average[2],"A")
print("Average Charge:",average[3],"%")
print("Max Temperature:",np.max(d[:,0]),"degree Celsius")
print("Min Temperature:",np.min(d[:,0]),"degree Celsius")
print("voltage Column:")
print(d[:,1])
high_temp=d[d[:,0]>40]
print("High Temperature Readings")
print(high_temp)
low_battery=d[d[:,3]<50]
print("Low Battery Readings")
print(low_battery)

Shape: (5, 4)
Average Temperature: 38.4 degree Celsius
Average Voltage: 388.0 v
Average Current: 25.8 A
Average Charge: 74.2 %
Max Temperature: 45 degree Celsius
Min Temperature: 32 degree Celsius
voltage Column:
[400 395 390 380 375]
High Temperature Readings
[[ 42 380  30  60]
 [ 45 375  32  48]]
Low Battery Readings
[[ 45 375  32  48]]


In [3]:
import numpy as np
A=np.array([[2,1],
            [1,3]])
X=np.array([[40],[25]])
Y=np.dot(A,X)
print("Transformed Output Y:")
print(Y)
print("\nTranspose of A:")
print(A.T)
print("\nDeterminant of A:")
print(np.linalg.det(A))
print("\nInverse of A:")
print(np.linalg.inv(A))
B=np.array([[100],[120]])
Solution=np.linalg.solve(A,B)
print("\nSolution of AX=B:")
print(Solution)
print("X=",Solution[0][0])
print("Y=",Solution[1][0])

Transformed Output Y:
[[105]
 [115]]

Transpose of A:
[[2 1]
 [1 3]]

Determinant of A:
5.000000000000001

Inverse of A:
[[ 0.6 -0.2]
 [-0.2  0.4]]

Solution of AX=B:
[[36.]
 [28.]]
X= 36.0
Y= 28.0


In [4]:
import sympy as sp
t=sp.symbols('t')
c=100-2*t-sp.Rational(1,2)*t**2
dcdt=sp.diff(c,t)
print("charge function:",c)
print("Rate of change dc/dt:", dcdt)
print(dcdt)
rate_2=dcdt.subs(t,2)
rate_5=dcdt.subs(t,5)
print("Rate of change at t=2:",rate_2)
print("Rate of change at t=5:",rate_5)
if abs(rate_5)>abs(rate_2):
  print("The battery is losing charge at an increasing rate")
else:
  print("The battery is losing charge at a decreasing rate")

charge function: -t**2/2 - 2*t + 100
Rate of change dc/dt: -t - 2
-t - 2
Rate of change at t=2: -4
Rate of change at t=5: -7
The battery is losing charge at an increasing rate


In [5]:
import numpy as np
d=np.array([
    [32,400,20,95],
    [35,395,22,88],
    [38,390,25,80],
    [42,380,30,60],
    [45,375,32,48]
])
avg=np.mean(d,axis=0)
charge_loss=d[0,3] - d[-1,3]
high_temp=d[d[:,0]>40][0]
A=np.array([[2,1],
            [1,3]])
X=np.array([[40],[25]])
Y=A@X
B=np.array([[100],[120]])
solution=np.linalg.solve(A,B)
print("Battery Peformance Report")
print("avg temp:",avg[0],"degree Celsius")
print("avg voltage:",avg[1],"v")
print("avg current:",avg[2],"A")
print("avg charge:",avg[3],"%")
print("Total charge loss:", charge_loss, "%")
print("First high temperature reading:",high_temp[0],"degree Celsius")
print("Transformed Output Y:")
print(Y)
print("X=",solution[0])
print("Y=",solution[1])
print("Discharge rate at 2hrs:-4%/hr")
print("Discharge rate at 5hrs:-7%/hr")
print("Final Decision: monitor")

Battery Peformance Report
avg temp: 38.4 degree Celsius
avg voltage: 388.0 v
avg current: 25.8 A
avg charge: 74.2 %
Total charge loss: 47 %
First high temperature reading: 42 degree Celsius
Transformed Output Y:
[[105]
 [115]]
X= [36.]
Y= [28.]
Discharge rate at 2hrs:-4%/hr
Discharge rate at 5hrs:-7%/hr
Final Decision: monitor
