In [ ]:
import numpy as np
arr = np.array([1, 2, 3, 4])
print(arr)

[1 2 3 4]


In [ ]:
arr = np.zeros((4,4))
print(arr)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


3. Generate Numbers from 1 to 9

---



In [ ]:
arr = np.arange(1,10)
print(arr)

[1 2 3 4 5 6 7 8 9]


Reshape an Array

In [ ]:
arr = np.arange(1,13)
print(arr.reshape(3,4))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


Find Shape and Size

In [ ]:
arr = np.array([[10,20,30],[40,50,60]])
print(arr.shape)
print(arr.size)

(2, 3)
6


np.linspace() : Creates evenly spaced numbers between a start and end value.

In [ ]:
arr = np.linspace(2, 8, 4)
print(arr)

[2. 4. 6. 8.]


np.eye() : Creates an Identity Matrix (1s on the diagonal and 0s elsewhere).  syntax : np.eye(rows, columns)

In [ ]:
arr = np.eye(5)
print(arr)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


np.full() :Creates an array filled with the same value.Syntax :np.full(shape, value)

In [ ]:
arr = np.full((3, 4), 8)
print(arr)

[[8 8 8 8]
 [8 8 8 8]
 [8 8 8 8]]


In [ ]:
arr = np.array([[1, 2, 3],[4, 5, 6]])
print(arr.shape)
print(arr.ndim)
print(arr.size)
print(arr.dtype)
print(arr.T)

(2, 3)
2
6
int64
[[1 4]
 [2 5]
 [3 6]]


A 3-D NumPy array has 3 dimensions:
Depth (Layers)
Rows
Columns
syntax:
import numpy as np

array_name = np.array([
    [
        [element1, element2, ...],
        [element3, element4, ...]
    ],
    [
        [element5, element6, ...],
        [element7, element8, ...]
    ]
])

In [ ]:

arr = np.array([
    [[10, 20, 30],
     [40, 50, 60]],

    [[70, 80, 90],
     [10, 11, 12]]
])

print(arr)
print(arr.ndim)
print(arr.shape)
print(arr.size)
print(arr[0])
print(arr[1])
print(arr[0][1])
print(arr[1][0][0])

[[[10 20 30]
  [40 50 60]]

 [[70 80 90]
  [10 11 12]]]
3
(2, 2, 3)
12
[[10 20 30]
 [40 50 60]]
[[70 80 90]
 [10 11 12]]
[40 50 60]
70


reshape() Function
Purpose
The reshape() function changes the shape (dimensions) of an array without changing its data.
Syntax :
np.reshape(array_name, (rows, columns))

In [ ]:
import numpy as np
arr = np.array([10, 20, 30, 40, 50, 60])
new_arr = arr.reshape(2, 3)
print(new_arr)

[[10 20 30]
 [40 50 60]]


In [ ]:
arr = np.array([10, 20, 30, 40, 50, 60])
new_arr_1 = np.reshape(arr,(3,2))
print(new_arr_1)

[[10 20]
 [30 40]
 [50 60]]


In [ ]:
arr_3d = np.array([10,20,30,40,50,60,70,80])
new_arr_3d = arr_3d.reshape(2,2,2)
print(new_arr_3d)

[[[10 20]
  [30 40]]

 [[50 60]
  [70 80]]]


1-D :
Syntax :
array_name[start:stop:step]

In [ ]:
import numpy as np
arr = np.array([1,2,3,4,5,6])
print(arr[1:5])
print(arr[:4])
print(arr[2:])
print(arr[::2])

[2 3 4 5]
[1 2 3 4]
[3 4 5 6]
[1 3 5]


Slicing in 2-D Array:
Syntax:
array_name[row_start:row_end, col_start:col_end]

In [ ]:
import numpy as np
arr = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])
print(arr[0:2,1:3])
print(arr[1,:])
print(arr[:,2])

[[2 3]
 [5 6]]
[4 5 6]
[3 6 9]


Slicing in 3-D Array:



In [ ]:
import numpy as np
arr = np.array([
    [[10,20,30],[40,50,60]],
    [[70,80,90],[10,11,12]]
])
print(arr[0,:,:])
print(arr[1,1,:])
print(arr[:,:,0])

[[10 20 30]
 [40 50 60]]
[10 11 12]
[[10 40]
 [70 10]]


NumPy Arithmetic, Mathematical, and Statistical Functions

In [ ]:
import numpy as np

a = np.array([1,2,3])
b = np.array([2,4,5])
print("Addition:", a+b)
print("Subtraction:", a-b)
print("Multiplication:", a*b)
print("Division:", a/b)
print("Floor Division:", a//b)
print("Modulus:", a%b)
print("Power:", a**2)

Addition: [3 6 8]
Subtraction: [-1 -2 -2]
Multiplication: [ 2  8 15]
Division: [0.5 0.5 0.6]
Floor Division: [0 0 0]
Modulus: [1 2 3]
Power: [1 4 9]


In [ ]:
import numpy as np

arr = np.array([2, 4, 8, 16, 24])
print("Original Array:", arr)

print("\nSquare Root:", np.sqrt(arr))

print("Square:", np.square(arr))

print("Cube:", np.power(arr, 3))

arr2 = np.array([-5, -10, 15, -20, 25])
print("\nAbsolute Value:", np.abs(arr2))

print("\nExponential:", np.exp(arr))

print("\nNatural Log:", np.log(arr))

print("Log Base 10:", np.log10(arr))

print("\nSine:", np.sin(arr))

print("Cosine:", np.cos(arr))

print("Tangent:", np.tan(arr))

decimal = np.array([2.34, 4.67, 8.91, 6.28])
print("\nRounded Values:", np.round(decimal))

print("Ceiling:", np.ceil(decimal))

print("Floor:", np.floor(decimal))

Original Array: [ 2  4  8 16 24]

Square Root: [1.41421356 2.         2.82842712 4.         4.89897949]
Square: [  4  16  64 256 576]
Cube: [    8    64   512  4096 13824]

Absolute Value: [ 5 10 15 20 25]

Exponential: [7.38905610e+00 5.45981500e+01 2.98095799e+03 8.88611052e+06
 2.64891221e+10]

Natural Log: [0.69314718 1.38629436 2.07944154 2.77258872 3.17805383]
Log Base 10: [0.30103    0.60205999 0.90308999 1.20411998 1.38021124]

Sine: [ 0.90929743 -0.7568025   0.98935825 -0.28790332 -0.90557836]
Cosine: [-0.41614684 -0.65364362 -0.14550003 -0.95765948  0.42417901]
Tangent: [-2.18503986  1.15782128 -6.79971146  0.30063224 -2.1348967 ]

Rounded Values: [2. 5. 9. 6.]
Ceiling: [3. 5. 9. 7.]
Floor: [2. 4. 8. 6.]


In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
import numpy as np

marks = np.array([55, 67, 74, 81, 89, 92, 63])

print("Original Array:", marks)

print("Sorted Array:", np.sort(marks))

print("Sum:", np.sum(marks))

print("Mean:", np.mean(marks))

print("Median:", np.median(marks))

print("Maximum:", np.max(marks))

print("Minimum:", np.min(marks))

print("Range:", np.ptp(marks))

print("Standard Deviation:", np.std(marks))

print("Variance:", np.var(marks))

print("Index of Maximum:", np.argmax(marks))

print("Index of Minimum:", np.argmin(marks))

print("25th Percentile:", np.percentile(marks, 25))

print("50th Percentile:", np.percentile(marks, 50))

print("75th Percentile:", np.percentile(marks, 75))

Original Array: [75 82 90 68 95 88 79]
Sorted Array: [68 75 79 82 88 90 95]

Sum: 577
Mean: 82.42857142857143
Median: 82.0
Maximum: 95
Minimum: 68
Range: 27
Standard Deviation: 8.633111388421788
Variance: 74.53061224489797
Index of Maximum: 4
Index of Minimum: 3
25th Percentile: 77.0
50th Percentile: 82.0
75th Percentile: 89.0
